### ISSUE TITLE
nunjucks 2.2.0 uses a version of nunjucks-slim.js incompatible with pre-compilation

### ISSUE THREAD

**Issue by mrehayden1** [sindresorhus/gulp-nunjucks#12]
Could we get an upgrade to 2.3+, which has the correct version of nunjucks-slim.js, to work around this?

I could try to do a PR myself.

**Comment by mrehayden1** [comment]
Mixing nunjucks-slim v.2.3 with output from gulp-nunjucks 2.2.0 seems to work.

I'll keep testing to see if it's a likely solution.

**Comment by sindresorhus** [comment]
Just reinstall this plugin to get the latest Nunjucks, thanks to semver.

https://github.com/sindresorhus/gulp-nunjucks/blob/1c80b2f9039ccb43eae18b8262966f5575542ce6/package.json#L37

https://nodesource.com/blog/semver-tilde-and-caret
