### ISSUE TITLE
Configure

### ISSUE THREAD

**Issue by mfundo** [sindresorhus/gulp-nunjucks#17]
Hi Sindresorhus,

Trying to use your gulp plugin but not sure how to pass through options that go into nunjucks.configure() ?

Another silly question, is there away I can avoid using relative paths for my includes?
instead of: "  ../../component/componentName/fileName.nunjucks "
I want:  " componentName/fileName.nunjucks "

Thanks

**Comment by sindresorhus** [comment]
From the readme:

> Options will be passed directly to the Nunjucks [Environment constructor](https://mozilla.github.io/nunjucks/api.html#constructor) which will be used to compile templates.

> Another silly question, is there away I can avoid using relative paths for my includes?

That would be a question for a Nunjucks support channel.
