### ISSUE TITLE
Extension remains .html when running precompile

### ISSUE THREAD

**Issue by froddd** [sindresorhus/gulp-nunjucks#26]
The example given for `precompile` creates the file `dist/greeting.html` instead of `dist/greeting.js`.

**Comment by sindresorhus** [comment]
That's weird. The tests are passing with `.js` extension: https://github.com/sindresorhus/gulp-nunjucks/blob/809cea0a7eb43975ee9a6071ee2be811d7d27d3d/test.js#L12 Maybe try `rm -rf node_modules && npm install`

**Comment by froddd** [comment]
`rm -rf node_modules && npm install` doesn't fix it, unfortunately.

Is setting the extension using `file.extname = '.js'` a Vinyl-only thing? https://github.com/gulpjs/vinyl#fileextname

Pull request: https://github.com/sindresorhus/gulp-nunjucks/pull/27
