### ISSUE TITLE
Nunjucks Incompatibility runtime.fromIterator Error

### ISSUE THREAD

**Issue by NatEvatt** [sindresorhus/gulp-nunjucks#32]
Recently I have been getting the error `TypeError: runtime.fromIterator is not a function` whenever I try using a precompiled template with a `for` statement.  I figured out that the issue is related to nunjucks version as described in this post on the nunjucks github page https://github.com/mozilla/nunjucks/issues/1091

I have been able to fix the issue by forcing npm to install nunjucks 3.0.x as described in the url above.  It would be awesome if gulp-nunjucks were updated to the current 3.1.x.

Thanks

**Comment by sindresorhus** [comment]
Done
