### ISSUE TITLE
Undefined value of template function argument

### ISSUE THREAD

**Issue by pilaas** [sindresorhus/gulp-nunjucks#9]
Hello,

I've decided to report this issue here, not in nunjucks repository, mainly because the problem occured after I've upgraded gulp-nunjucks to 2.1.1, regardless of the version of nunjucks.

As the title says, when I'm invoking function with argument within template, the value of the argument is undefined. It works when I'm using gulp-nunjucks@1.0.3. I haven't tried anything between these two versions.

My first thought was to try switch nunjucks version, unfortunately with no effect.
Only downgrading gulp-nunjucks version helped.

**Comment by sindresorhus** [comment]
Other than the Nunjucks bump, the only real changes since 1.0.3 were https://github.com/sindresorhus/gulp-nunjucks/commit/8e054d48ea4a4b046ae86438d4c1de27bfae6095 (by @d10) and https://github.com/sindresorhus/gulp-nunjucks/commit/dcd750ad7bef52fa0b2cd6c3f16ef732dab0846e (by @renanvaz).

**Comment by renanvaz** [comment]
@sindresorhus I have changed only one line of code in my commit (in compile method).
@pilaas It is a error of compile or precompíle?

**Comment by d10** [comment]
Not too sure what you mean @pilaas :cry: could you provide some simple code that fails?

**Comment by pilaas** [comment]
@renanvaz Precompile. I'll soon paste here some example code. "Hope" it will also fail.

**Comment by pilaas** [comment]
My bad. I haven't upgraded browser nunjucks and it seems it wasn't working with an output of upgraded gulp-nunjuck. Sorry for the confusion.
